console.log("WELCOME")
console.log(">>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<")
console.log("|DAFTAR DATA LAMANYA JAM KERJA|")
console.log(">>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<")

//Data Jam Kerja
var a = [[16,10],[20,55]];
var b = [[20,40],[22,60]];
var c = [[23,60],[24,60]];
var d = [[5,60],[6,30]];
var e = [[15,60],[23,60]];
var f = [[17,60],[21,60]];
var g = [[2,60],[4,60]];
var h = [[19,30],[21,30]];
var i = [[8,60],[16,60]];
var j = [[16,60],[23,60]];
var k = [[17,00],[18,15]];
var l = [[7,60],[9,60]];
var m = [[14,60],[30,60]];
var n = [[00,00],[1,30]];
var o = [[5,10],[23,60]];

//Rumus

var jam_a = a[1][0] - a[0][0];
var jam_1 = a[1][1] - a[0][1];

var jam_b = b[1][0] - b[0][0];
var jam_2 = b[1][1] - b[0][1];

var jam_c = c[1][0] - c[0][0];
var jam_3 = c[1][1] - c[0][1];

var jam_d = d[1][0] - d[0][0];
var jam_4 = d[0][1] - d[1][1];

var jam_e = e[1][0] - e[0][0];
var jam_5 = e[1][1] - e[0][1];

var jam_f = f[1][0] - f[0][0];
var jam_6 = f[1][1] - f[0][1];

var jam_g = g[1][0] - g[0][0];
var jam_7 = g[1][1] - g[0][1];

var jam_h = h[1][0] - h[0][0];
var jam_8 = h[1][1] - h[0][1];

var jam_i = i[1][0] - i[0][0];
var jam_9 = i[1][1] - i[0][1];

var jam_j = j[1][0] - j[0][0];
var jam_10 = j[1][1] - j[0][1];

var jam_k = k[1][0] - k[0][0];
var jam_11 = k[1][1] - k[0][1];

var jam_l = l[1][0] - l[0][0];
var jam_12 = l[1][1] - l[0][1];

var jam_m = m[0][0] - m[1][0];
var jam_13 = m[1][1] - m[0][1];

var jam_n = n[1][0] - n[0][0];
var jam_14 = n[1][1] - n[0][1];

var jam_o = o[1][0] - o[0][0];
var jam_15 = o[1][1] - o[0][1];


//Hasil
console.log("1.  DIMAS   = "+jam_a+" "+"JAM"+"    "+jam_1+" "+"MENIT");
console.log("-----------------------------------------------------");
console.log("2.  RAIHAN  = "+jam_b+" "+"JAM"+"    "+jam_2+" "+"MENIT");
console.log("-----------------------------------------------------");
console.log("3.  ILHAM   = "+jam_c+" "+"JAM"+"    "+jam_3+" "+"MENIT");
console.log("-----------------------------------------------------");
console.log("4.  FIKRY   = "+jam_d+" "+"JAM"+"    "+jam_4+" "+"MENIT");
console.log("-----------------------------------------------------");
console.log("5.  JHORDY  = "+jam_e+" "+"JAM"+"    "+jam_5+" "+"MENIT");
console.log("-----------------------------------------------------");
console.log("6.  KRESNA  = "+jam_f+" "+"JAM"+"    "+jam_6+" "+"MENIT");
console.log("-----------------------------------------------------");
console.log("7.  SUTNA   = "+jam_g+" "+"JAM"+"    "+jam_7+" "+"MENIT");
console.log("-----------------------------------------------------");
console.log("8.  TIARA   = "+jam_h+" "+"JAM"+"    "+jam_8+" "+"MENIT");
console.log("-----------------------------------------------------");
console.log("9.  SINDY   = "+jam_i+" "+"JAM"+"    "+jam_9+" "+"MENIT");
console.log("-----------------------------------------------------");
console.log("10. NIA     = "+jam_j+" "+"JAM"+"    "+jam_10+" "+"MENIT");
console.log("-----------------------------------------------------");
console.log("11. LORENZO = "+jam_k+" "+"JAM"+"    "+jam_11+" "+"MENIT");
console.log("-----------------------------------------------------");
console.log("12. ANRIAN  = "+jam_l+" "+"JAM"+"    "+jam_12+" "+"MENIT");
console.log("-----------------------------------------------------");
console.log("13. AL      = "+jam_m+" "+"JAM"+"    "+jam_13+" "+"MENIT");
console.log("-----------------------------------------------------");
console.log("14. ANDRI   = "+jam_n+" "+"JAM"+"    "+jam_14+" "+"MENIT");
console.log("-----------------------------------------------------");
console.log("15. ANDROW  = "+jam_o+" "+"JAM"+"    "+jam_15+" "+"MENIT");
console.log("-----------------------------------------------------");

console.log(" ")
console.log("THANK YOU")

